name: Endor Labs Scan
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
      inputs:
        namespace:
          description: "Enter your Endor Labs tenant name:"
          required: true

jobs:
  scan:
    permissions:
      contents: read
      id-token: write
    
    runs-on: ubuntu-latest
  
    steps:
    - name: Setup namespace
      id: namespace-setup 
      run: | 
        echo "::add-mask::${{ github.event.inputs.namespace }}" 
        echo "NAMESPACE=${{ github.event.inputs.namespace }}" >> $GITHUB_ENV
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'microsoft'
        java-version: '17'
        cache: 'maven'
    
    - name: Compile Package
      run: mvn clean install
    
    - name: Run endorctl
      uses: endorlabs/github-action@v1.1.2
      with:
        namespace: "$NAMESPACE"
        enable_github_action_token: true
        scan_summary_output_type: "table"
        additional_args: "--as-default-branch"
        pr: false
        
    
